import { motion } from 'framer-motion'
import { useInView } from 'react-intersection-observer'
import SectionHeader from './SectionHeader'

const bullets = [
  <>Contributed to an <strong>AI-powered database interaction platform</strong> enabling natural language querying, reducing manual SQL effort by <strong>~60%</strong> for common data access tasks.</>,
  <>Developed responsive frontend interfaces using <strong>React and Next.js</strong>, enabling users to submit prompts and visualize structured query responses generated by the AI system.</>,
  <>Integrated <strong>4+ relational database systems</strong> into a unified query layer, enabling dynamic data retrieval across multiple datasets through prompt-based querying.</>,
  <>Collaborated with backend engineers to design and optimize <strong>REST API interactions</strong>, improving query response reliability and reducing average API latency by <strong>~25%</strong>.</>,
  <>Containerized application services using <strong>Docker</strong>, enabling consistent development environments and streamlined deployment workflows.</>,
]

export default function Experience() {
  const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.1 })

  return (
    <section id="experience" style={{ padding: '100px 0', position: 'relative', zIndex: 1 }}>
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 40px' }}>
        <SectionHeader label="// work experience" title="Where I've Worked" />

        <div ref={ref} style={{ position: 'relative', paddingLeft: 32 }}>
          {/* timeline line */}
          <div style={{
            position: 'absolute', left: 0, top: 12, bottom: 0,
            width: 1,
            background: 'linear-gradient(to bottom, #6366f1, transparent)',
          }} />

          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={inView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.6 }}
            style={{
              position: 'relative',
              background: 'rgba(255,255,255,0.04)',
              border: '1px solid rgba(255,255,255,0.08)',
              borderRadius: 16, padding: '32px 36px',
              backdropFilter: 'blur(10px)',
              transition: 'border-color 0.3s, box-shadow 0.3s',
            }}
            whileHover={{ borderColor: 'rgba(99,102,241,0.4)', boxShadow: '0 0 40px rgba(99,102,241,0.1)' }}
          >
            {/* dot */}
            <div style={{
              position: 'absolute', left: -40, top: 32,
              width: 14, height: 14, borderRadius: '50%',
              background: '#6366f1', border: '3px solid #050810',
              boxShadow: '0 0 0 3px rgba(99,102,241,0.3)',
            }} />

            <div style={{
              display: 'flex', justifyContent: 'space-between',
              alignItems: 'flex-start', flexWrap: 'wrap', gap: 8, marginBottom: 8,
            }}>
              <div>
                <div style={{ fontSize: '1.1rem', fontWeight: 700, color: '#e2e8f0', marginBottom: 4 }}>
                  Software Developer
                </div>
                <div style={{
                  display: 'flex', alignItems: 'center', gap: 6,
                  color: '#6366f1', fontSize: '0.88rem', fontWeight: 600,
                }}>
                  <i className="fas fa-building" style={{ fontSize: '0.75rem' }} />
                  DX Engineers
                </div>
              </div>
              <div style={{
                fontFamily: "'JetBrains Mono',monospace", fontSize: '0.78rem',
                color: '#475569', background: 'rgba(255,255,255,0.05)',
                border: '1px solid rgba(255,255,255,0.08)',
                padding: '5px 12px', borderRadius: 6,
              }}>
                Sep 2022 – Sep 2023
              </div>
            </div>

            <ul style={{ listStyle: 'none', marginTop: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
              {bullets.map((b, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  animate={inView ? { opacity: 1, x: 0 } : {}}
                  transition={{ duration: 0.4, delay: 0.1 + i * 0.07 }}
                  style={{
                    color: '#94a3b8', fontSize: '0.88rem', lineHeight: 1.75,
                    paddingLeft: 18, position: 'relative',
                  }}
                >
                  <span style={{ position: 'absolute', left: 0, color: '#6366f1' }}>▹</span>
                  {b}
                </motion.li>
              ))}
            </ul>

            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 24 }}>
              {['React', 'Next.js', 'Node.js', 'REST API', 'Docker', 'SQL'].map(t => (
                <span key={t} style={{
                  fontFamily: "'JetBrains Mono',monospace",
                  fontSize: '0.72rem', color: '#06b6d4',
                  background: 'rgba(6,182,212,0.08)',
                  border: '1px solid rgba(6,182,212,0.2)',
                  padding: '3px 9px', borderRadius: 5,
                }}>{t}</span>
              ))}
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
